import matplotlib.pyplot as plt
import numpy as np
expid="102"
a,x,j1,g1=np.loadtxt('../data/cost_function_gradient_'+expid+'_03.dat',unpack=True)
a,x,j2,g2=np.loadtxt('../data/cost_function_gradient_'+expid+'_09.dat',unpack=True)
a,x,j3,g3=np.loadtxt('../data/cost_function_gradient_'+expid+'_15.dat',unpack=True)
a,x,j4,g4=np.loadtxt('../data/cost_function_gradient_'+expid+'_18.dat',unpack=True)
a,x,j5,g5=np.loadtxt('../data/cost_function_gradient_'+expid+'_21.dat',unpack=True)
fig=plt.figure()
ax1=fig.add_subplot(121)
ax1.plot(x,j1,label='03 h',linewidth=2,color='red')
ax1.plot(x,j2,label='09 h',linewidth=2,color='black')
ax1.plot(x,j3,label='15 h',linewidth=2,color='green')
ax1.plot(x,j4,label='18 h',linewidth=2,color='blue')
ax1.plot(x,j5,label='21 h',linewidth=2,color='orange')
#ax1.set_ylim(0,500)
ax1.set_xlim(0,20)
ax1.set_xticks(np.arange(0,21,4))
ax1.legend(loc='best')
ax1.set_title('Total cost-function J')
ax1.set_xlabel('Iterations')
ax1.set_ylabel('Jtot')
ax2=fig.add_subplot(122)
ax2.semilogy(x,g1,label='03 h',linewidth=2,color='red')
ax2.semilogy(x,g2,label='09 h',linewidth=2,color='black')
ax2.semilogy(x,g3,label='15 h',linewidth=2,color='green')
ax2.semilogy(x,g4,label='18 h',linewidth=2,color='blue')
ax2.semilogy(x,g5,label='21 h',linewidth=2,color='orange')
ax2.set_xlim(0,20)
ax2.set_xticks(np.arange(0,21,4))
ax2.legend(loc='best')
ax2.set_title('Gradient of J')
ax2.set_xlabel('Iterations')
ax2.set_ylabel('Norm of gradient')
figure = plt.gcf()
figure.set_size_inches(10, 5)
plt.savefig('../plots/Figure_JG_3DVar_102b.png',dpi=600)
plt.show()


