import matplotlib.pyplot as plt
import numpy as np
x,j1,g1=np.loadtxt('../data/cost_function_gradient_001.dat',unpack=True)
x,j2,g2=np.loadtxt('../data/cost_function_gradient_002.dat',unpack=True)
x,j3,g3=np.loadtxt('../data/cost_function_gradient_003.dat',unpack=True)
x,j4,g4=np.loadtxt('../data/cost_function_gradient_004.dat',unpack=True)
x,j11,g11=np.loadtxt('../data/cost_function_gradient_009.dat',unpack=True)
x,j22,g22=np.loadtxt('../data/cost_function_gradient_010.dat',unpack=True)
x,j33,g33=np.loadtxt('../data/cost_function_gradient_011.dat',unpack=True)
x,j44,g44=np.loadtxt('../data/cost_function_gradient_012.dat',unpack=True)
fig=plt.figure()
ax1=fig.add_subplot(121)
ax1.plot(x,j1,label='24 h',linewidth=3,color='red')
ax1.plot(x,j2,label='12 h',linewidth=3,color='black')
ax1.plot(x,j3,label='06 h',linewidth=3,color='green')
ax1.plot(x,j4,label='03 h',linewidth=3,color='blue')
ax1.plot(x,j11,label='24 h',linewidth=1,color='red')
ax1.plot(x,j22,label='12 h',linewidth=1,color='black')
ax1.plot(x,j33,label='06 h',linewidth=1,color='green')
ax1.plot(x,j44,label='03 h',linewidth=1,color='blue')
ax1.set_ylim(0,450)
ax1.set_xlim(0,20)
ax1.set_xticks(np.arange(0,21,4))
ax1.legend(loc='best')
ax1.set_title('Total cost-function J')
ax1.set_xlabel('Iterations')
ax1.set_ylabel('Jtot')
ax2=fig.add_subplot(122)
ax2.semilogy(x,g1,label='24 h',linewidth=3,color='red')
ax2.semilogy(x,g2,label='12 h',linewidth=3,color='black')
ax2.semilogy(x,g3,label='06 h',linewidth=3,color='green')
ax2.semilogy(x,g4,label='03 h',linewidth=3,color='blue')
ax2.semilogy(x,g11,label='24 h',linewidth=1,color='red')
ax2.semilogy(x,g22,label='12 h',linewidth=1,color='black')
ax2.semilogy(x,g33,label='06 h',linewidth=1,color='green')
ax2.semilogy(x,g44,label='03 h',linewidth=1,color='blue')
ax2.set_xlim(0,20)
ax2.set_xticks(np.arange(0,21,4))
ax2.legend(loc='best')
ax2.set_title('Gradient of J')
ax2.set_xlabel('Iterations')
ax2.set_ylabel('Norm of gradient')
figure = plt.gcf()
figure.set_size_inches(10, 5)
plt.savefig('../plots/Figure_JG_leap.png',dpi=600)
plt.show()


